### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by newschapmj1** [auth0-samples/auth0-javascript-samples#121]
auth_config.json
Remember to remove the curly braces around DOMAIN and CLIENT_ID, otherwise the Auth0 log in page will not load
In other words,  your unique DOMAIN AND CLIENT_ID should only be surrounded in double quotes.

{
  "domain": "{DOMAIN}",
  "clientId": "{CLIENT_ID}"
}

**Comment by mmszhezhi** [comment]
> auth_config.json Remember to remove the curly braces around DOMAIN and CLIENT_ID, otherwise the Auth0 log in page will not load In other words, your unique DOMAIN AND CLIENT_ID should only be surrounded in double quotes.
> 
> { "domain": "{DOMAIN}", "clientId": "{CLIENT_ID}" }
god damn!  you save me two hours!
