### ISSUE TITLE
invalid_token trying to log in

### ISSUE THREAD

**Issue by HeikerAraujo** [auth0-samples/auth0-javascript-samples#13]
Project: 03-Calling-an-API

error: invalid_token
errorDescripcion: "The token was issued in the future. Please check your computed clock.

![image](https://cloud.githubusercontent.com/assets/26749061/26567788/01b12920-44cc-11e7-84f3-88bfd779bb7f.png)

**Comment by ANDRES2A** [comment]
Hi, how did you solved it?

**Comment by chenkie** [comment]
You can either sync your system clock or you can set some leeway time. To set leeway, add this to your `WebAuth` config options:

```js
{
  // ...

  // 30 seconds of leeway
  leeway: 30
}
```

**Comment by ANDRES2A** [comment]
Thank you so much, it worked.
