### ISSUE TITLE
Error with the admin section

### ISSUE THREAD

**Issue by rafanog** [auth0-samples/auth0-javascript-samples#34]
Even though that the text in the "admin" section of the sample says that you need to have the "write:messages" scopes to see it, but the user's still available to access without that scope

![image](https://user-images.githubusercontent.com/15782359/34785737-6bd33094-f608-11e7-8176-f98bbf52cc9f.png)

**Comment by luisrudge** [comment]
I'm cleaning up some stale issues and it's been a while since this issue was opened. 🗑
