### ISSUE TITLE
Error while renewing the token of an external IdP

### ISSUE THREAD

**Issue by rafanog** [auth0-samples/auth0-javascript-samples#35]
This error's shown while trying to renew the access_token after log in with a google or a linkedin account 
![image](https://user-images.githubusercontent.com/15782359/34785866-cd60dff0-f608-11e7-84fc-58a980b8f39f.png)

**Comment by stevehobbsdev** [comment]
@rafanog This can be down to using the Google dev keys with your Auth0 account, which [presents some caveats](https://auth0.com/docs/connections/social/devkeys). I would expect the problem to go away when using keys from a real Google account.
