### ISSUE TITLE
Sample 01-login crash

### ISSUE THREAD

**Issue by adriatic** [auth0-samples/auth0-javascript-samples#37]
The sample [01-login](https://github.com/auth0-samples/auth0-javascript-samples/tree/master/01-Login), probably the oldest of all samples has a problem:

```
app.js:28 Uncaught TypeError: Cannot read property 'style' of null
    at HTMLButtonElement.<anonymous> (app.js:28)
(anonymous) @ app.js:28
```

The problem is that at the click on the `Home` button after that app is loaded, invokes the following code

```
 homeViewBtn.addEventListener('click', function() {
    homeView.style.display = 'inline-block';
    loginView.style.display = 'none';
  });
```
where the `loginView` is null - because it is not properly initialized, shown below:

![image](https://user-images.githubusercontent.com/2712405/38643585-9a88a320-3dab-11e8-9518-3501c034d791.png)

This is the consequence of the fact that the entity 'login-view' does not exist.

P.S.
While one can say that this is a completely trivial issue, not worthy of a discussion, I disagree: the tutorial samples ought to be flawless 😄

**Comment by aaguiarz** [comment]
Hi! Thanks for reporting it!

**Comment by adriatic** [comment]
Hi Andres - I am the same guy who offered the Aurelia samples. Before adding all the 01 - 06 ones I wanted to check the plain JavaScript versions. So, I expect that you will hear more form me 😄

**Comment by aaguiarz** [comment]
Yes, I noticed you were the same guy ;). All feedback is welcome!

**Comment by adriatic** [comment]
@aaguiarz I did not say that this problem with undefined `loginView` is present throughout the **[auth0-javascript-samples](https://github.com/auth0-samples/auth0-javascript-samples)** collection.

I am also sure that once I pointed out the issue in 01-Login sample, you realized this 😏

**Comment by stevehobbsdev** [comment]
Hi @adriatic, the samples have since been updated and this issue should no longer be present. If you feel there is still an issue, feel free to raise another.

**Comment by adriatic** [comment]
Since I wrote my issues more than a year , I gave up on waiting to see any response. In addition most of the problems I pointed out were trivial, so there is no need for me to verify that they are fixed by now.
