### ISSUE TITLE
Sample 02-User-Profile references old version of Auth0

### ISSUE THREAD

**Issue by adriatic** [auth0-samples/auth0-javascript-samples#38]
The **[02-user-profile](https://auth0.com/docs/quickstart/spa/vanillajs/02-user-profile)** quick start states 

> To learn more about the information returned by the /userinfo endpoint, see the **[/userinfo](https://auth0.com/docs/api/authentication#user-profile)** endpoint documentation.

The referred section describes Get User Info API and the screen shot below shows the problem

![image](https://user-images.githubusercontent.com/2712405/38683140-c7f582a8-3e3a-11e8-9814-3e4f39d6ac88.png)

**Comment by stevehobbsdev** [comment]
Thanks @adriatic. The samples have since been updated to use a [totally new version of the SDK](https://github.com/auth0/auth0-spa-js). If you're still having trouble, feel free to raise another issue.

**Comment by adriatic** [comment]
Since I wrote my issues more than a year , I gave up on waiting to see any response. In addition most of the problems I pointed out were trivial, so there is no need for me to verify that they are fixed by now.
