### ISSUE TITLE
03-Calling-an-API 

### ISSUE THREAD

**Issue by adriatic** [auth0-samples/auth0-javascript-samples#40]
Section **[Set the Audience and Scope in](https://auth0.com/docs/quickstart/spa/vanillajs/03-calling-an-api#set-the-audience-and-scope-in-auth0-webauth)** is in error:

Delete the first sentence in the paragraph below (as the API identifiers is already part of the **`auth0-variables.js`** file.

> ~~In your auth0.WebAuth instance, enter your API identifier as the value for audience.~~ Add your scopes to the scope key.

**Comment by stevehobbsdev** [comment]
Hey @adriatic , the sample app has been updated since this issue was raised. I'll close this issue for now; if you're still having trouble, please feel free to submit another issue.

**Comment by adriatic** [comment]
Hi Steve

Since I wrote my issues more than a year , I gave up on waiting to see any response. In addition most of the problems I pointed out were trivial, so there is no need for me to verify that they are fixed by now.
