### ISSUE TITLE
Encourage users to use yarn instead of npm

### ISSUE THREAD

**Issue by adriatic** [auth0-samples/auth0-javascript-samples#41]
I am using the latest npm & node and still get at slew of error messages on **`npm install`**, like: 
```
npm ERR! path C:\work\aurelia-identity\auth0\javascript\03-Calling-an-API\node_modules\fast-json-stable-stringify\package.json.3900822674
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename
npm ERR! Error: EPERM: operation not permitted, rename 'C:\work\aurelia-identity\auth0\javascript\03-Calling-an-API\node_modules\fast-json-stable-stringify\package.json.3900822674' -> 'C:\work\aurelia-identity\auth0\javascript\03-Calling-an-API\node_modules\fast-json-stable-stringify\package.json'
```
These could be caused by running vscode, or some virus checkers and even sublime editor  at the time of invoking **`npm install`**. I do not really believe that, as it ought to be a race condition in npm. By deleting **`node_modules`** folder and running **`yarn install`**, everything is fine.
```
λ yarn install
yarn install v1.5.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 9.04s.
```

**Comment by jimmyjames** [comment]
I wasn't able to reproduce this, and there has been changes to this sample since reporting. @adriatic if you are still experiencing this issue, please reopen and include the version of node and npm you are using.

**Comment by adriatic** [comment]
Given that this wes reported more than a year ago and nobody reacted in any way, closing this makes best sense
