### ISSUE TITLE
Sample 05-token-renewal fails

### ISSUE THREAD

**Issue by adriatic** [auth0-samples/auth0-javascript-samples#43]
After successful login, click on Renew Token button results with error message (on Chrome console):

```
 https://aurelia-identity.auth0.com/authorize?client_id=cxo2VDjr6kvQHEhWSJOxPyS2pK9Qxif9&response_type=token%20id_token&redirect_uri=http%3A%2F%2Flocalhost%3A3000&scope=openid%20profile&state=KKS5LuVlb5I-NADcH0lwKUk2bTwVtE70&nonce=4-oAoeRVcDjHFnIiZqS7VimOwQaoMR9R&response_mode=web_message&prompt=none&auth0Client=eyJuYW1lIjoiYXV0aDAuanMiLCJ2ZXJzaW9uIjoiOS40LjIifQ%3D%3D 400 (
```

The failure takes place in auth0.js, line 4595:

![image](https://user-images.githubusercontent.com/2712405/38742763-639e042a-3f0b-11e8-802e-aac3f9149bee.png)

After a few seconds the following alert shows up

![image](https://user-images.githubusercontent.com/2712405/38742891-af4eb8d8-3f0b-11e8-8d99-6e30879b72a9.png)

For  a while I tried to trace this through auth0.js code but gave up eventually.

**Comment by orocancourt** [comment]
I've got the exact same bug, it seems related to recent Chrome updates because the same code works fine with Firefox

**Comment by aaguiarz** [comment]
Hi

I just tried this, and it seems to be working fine. Did it end up working for you?

Thanks

**Comment by Stefanus-Januar** [comment]
@aaguiarz I also get same issue. 

Try to open iframe request and find this error.

![screen shot 2018-05-08 at 11 10 56 am 2](https://user-images.githubusercontent.com/6202701/39737672-b4519dc4-52b0-11e8-9f9b-1944d456b991.png)
 
Based on instruction, I have set Allowed Web Origins to http://localhost:3000

**Comment by Stefanus-Januar** [comment]
It turns out, I use login with google and cannot do refresh. 

Solved by login with auth0.
