### ISSUE TITLE
Problem with social login

### ISSUE THREAD

**Issue by rafanog** [auth0-samples/auth0-javascript-samples#5]
When using the social login option of the samples, there's no message shown that the login process was successful:

![image](https://cloud.githubusercontent.com/assets/15782359/25193755/1d986864-2506-11e7-9244-69bdc5ab1a88.png)

But the entry showing succesful login can be observed from the logs:
![image](https://cloud.githubusercontent.com/assets/15782359/25193793/3f729e0a-2506-11e7-88bf-b4df3b910f57.png)

Ticket: AUTH-3813

**Comment by luisrudge** [comment]
I believe this is no longer valid, considering we use the hosted login pages.
