### ISSUE TITLE
Sample 05-token-renewal: HTTP error 400

### ISSUE THREAD

**Issue by roelvz** [auth0-samples/auth0-javascript-samples#54]
Login works fine, but when clicking the Renew button, I get error code 400 (Failed to load resource: the server responded with a status of 400 ()). The response contains a HTML error page. I followed the README.md to the letter and changed nothing to the project (except for the auth.-variables.js).

**Comment by stevehobbsdev** [comment]
Hey @roelvz , the sample app has been updated since this issue was raised. I'll close this issue for now; if you're still having trouble, please feel free to submit another issue.
