### ISSUE TITLE
Can't logout

### ISSUE THREAD

**Issue by beno** [auth0-samples/auth0-javascript-samples#55]
After wrecking my brain over what I could possibly be doing wrong, I decided to try out one of the demo apps and lo and behold, the Login app shows exactly the same incomprehensible behaviour.

Steps:
- install en run app, click login
- show dialog, fill in credentials -> logged in
- click logout -> logged out
- click login -> logged in straight away

No matter how I clear all storage, cookies and what not, this unwanted behaviour persists. How is this possible?

Edit: happens on normal and incognito windows in Safari and Chrome.

**Comment by luisrudge** [comment]
The logout button only clears the local storage items. It means it's logging the user out of **your** application, not Auth0. 

https://github.com/auth0-samples/auth0-javascript-samples/blob/master/01-Login/app.js#L47

**Comment by beno** [comment]
But what use case does this support? A user who clicks logout expects to be actually logged out, correct? This leaves the door wide open and makes zero sense to me. How can I get it to behave normally?

**Comment by luisrudge** [comment]
If you want to also logout of Auth0’s servers, you need to call the `logout` method of Auth0js.

**Comment by luisrudge** [comment]
@beno thanks for the feedback. I'll ping someone from the quickstarts team to share their thoughts here.
