### ISSUE TITLE
Wrong parameter return_to in logout

### ISSUE THREAD

**Issue by marcfx** [auth0-samples/auth0-javascript-samples#63]
Based on auth.js doc, in logout should be used parameter returnTo and not return_to. 

https://github.com/auth0-samples/auth0-javascript-samples/blob/77eba03644a6bac25f82ea9fc0f99044152f0def/01-Login/app.js#L75

**Comment by stevehobbsdev** [comment]
Thanks @marcfx. This sample has since been rewritten and this change has been incorporated into that rewrite.
