### ISSUE TITLE
Fails to login, javascript console shows "Error: Invalid algorithm", logs attached.

### ISSUE THREAD

**Issue by eddo888** [auth0-samples/auth0-javascript-samples#72]
Logging in undefined
localhost/:1 Refused to apply style from 'http://localhost:3000/css/auth0-theme.min.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
Navigated to http://localhost:3000/?code=qj5ENkN1lgy47nb1&state=UWg1ZUx1MUZIbGV6SWM3aFIuUVh5T29iLkJkc2tTZE11X1hxVjkzb3VMdw%3D%3D
localhost/:1 Refused to execute script from 'http://localhost:3000/js/auth0-theme.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
app.js:105 > User not authenticated
app.js:111 > Parsing redirect
**app.js:121 Error parsing redirect: Error: Invalid algorithm**
    at ee (jwt.ts:65)
    at oe._verifyIdToken (Auth0Client.ts:76)
    at oe.<anonymous> (Auth0Client.ts:253)
    at Generator.next (<anonymous>)
    at a (tslib.es6.js:68)

**Comment by eddo888** [comment]
dave@valkyrie:~/git/github.com/auth0-samples/auth0-javascript-samples/01-Login
$ cat auth_config.json
{
  "domain": "pocketrocketsoftware.au.auth0.com",
  "clientId": "5QHfwJqw3OyQdADJaS2IU2j72r0KJvHC"
}

**Comment by luisrudge** [comment]
We added this error to our FAQ section: https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md#why-do-i-get-an-invalid-algorithm-error

**Comment by eddo888** [comment]
Cool, Thanks
