### ISSUE TITLE
Lock shows an incorrect message when user set a wrong email or password.

### ISSUE THREAD

**Issue by HeikerAraujo** [auth0-samples/auth0-javascript-samples#8]
When a user with wrong email or password tries to login, this shows: "WE'RE" When a user with a wrong email or password tries to login, Lock shows: "WE'RE SORRY, SOMETHING WENT WRONG WHEN ATTEMPTING LOG IN"
Project: 01-Embedded login using Lock version 10.16
The correct message should be:
"WRONG EMAIL OR PASSWORD"
![incorrectmessagelock](https://cloud.githubusercontent.com/assets/26749061/25921404/393aed0a-35a3-11e7-900f-3a619961be17.png)
Logs shows the error type below: "Failed Login (invalid email/username)"

**Comment by chenkie** [comment]
This is Lock related so closing here
