### ISSUE TITLE
Access denied error on Ubuntu 18.04

### ISSUE THREAD

**Issue by dabelsare** [auth0-samples/auth0-javascript-samples#84]
Hi There,

This is an issue with the JavaScript sample code .
I am facing an access denied error after a successful login on Ubuntu 18.04.
I get a 401 error when after login, auth0 tries hitting /oauth/token and returns {“error”:“access_denied”,“error_description”:“Unauthorized”}
The description is vague and I am just trying to run the sample code.
The same error is coming when I follow the quickstart to set up my code as well.

On windows sample code working fine, but same sample code not working on Ubuntu 18.04.

**Comment by aliakhtar** [comment]
Did you ever figure this out? I'm encountering the same thing
