### ISSUE TITLE
Failed Sign Up using email and password

### ISSUE THREAD

**Issue by HeikerAraujo** [auth0-samples/auth0-javascript-samples#9]
Project: 02-Custom-Login-Form
When a new user tries to register using their email and password
![signup](https://cloud.githubusercontent.com/assets/26749061/25926434/2bb397bc-35bd-11e7-852d-b8f2d9f6aeb3.png)

The result is: Oops!, something went wrong
![oops](https://cloud.githubusercontent.com/assets/26749061/25926485/914312a6-35bd-11e7-99cb-13329d24a350.png)

Logs shows the following information.
Type: Failed Login
Description: Password login is disabled for clients using externally hosted login pages with oidc_conformant flag set.
![logs](https://cloud.githubusercontent.com/assets/26749061/25926549/e69eb0ca-35bd-11e7-813a-11f5ec84330b.png)

**Comment by bortechteam** [comment]
I am facing the same problem.

**Comment by sonvirc** [comment]
Disable OIDC Conformant in advanced settings of Clients
![screen shot 2017-10-06 at 12 25 34 pm](https://user-images.githubusercontent.com/28830195/31266464-87da3200-aa91-11e7-8a4c-df10c3dcf53d.png)
