### ISSUE TITLE
mismatching_state: CSRF Warning! State not equal in request and response.

### ISSUE THREAD

**Issue by Torbson** [auth0-samples/auth0-javascript-samples#93]
When i test with localhost settings I get the following error after callback received a GET request:
`GET http://localhost:3000/callback?code=mKbAej-9voiiy7S3&state=bd97c12c065747d5a072ca4ad091d4d9`
> "mismatching_state: CSRF Warning! State not equal in request and response."

I tried to debug it, but I really do not understand it. The error seems to occur between
`return auth0.authorize_redirect(redirect_uri=AUTH0_CALLBACK_URL, audience=AUTH0_AUDIENCE)`
and
```
@app.route('/callback')
def callback_handling():
    auth0.authorize_access_token()

```

So there is not a lot of server.py code involved. The problem seems to occur on the auth0 side or at Authlib authorize_access_token().

As this is an example for auth0 usage in flask, help would be highly appreciated.

Thanks in advance

**Comment by alex-96-eng** [comment]
I also have this issue.

**Comment by frederikprijck** [comment]
The issue mentions python, while the repository is for JavaScript. I recommend opening another issue and elaborate accordingly with something for us to reproduce @mrcwinn
